name: plant_illness_detection
description: A mobile app to detect plant illnesses for lettuce, strawberries, and blueberries.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  fl_chart: ^0.66.0
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  http: ^1.2.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - .env
